version: '3.3'
services:
    awvs-nessus:
        ports:
            - '13443:3443'
            - '8834:8834'
        image: 'leishianquan/awvs-nessus:latest'
        command: bash -c "/etc/init.d/nessusd start"
